{% set name = "parmoo" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/parmoo-{{ version }}.tar.gz
  sha256: 233947da7d43854dcd46079236fcdbcddd957f6dc8bd603b8a97082f1c452386

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - pydoe
    - pandas
    - libensemble
    - plotly
    - dash
    - python-kaleido

test:
  imports:
    - parmoo
  commands:
    - py.test --pyargs parmoo.tests.unit_tests
  requires:
    - pytest

about:
  home: https://github.com/parmoo/parmoo
  summary: Python library for parallel multiobjective simulation optimization
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thchang
